### ISSUE TITLE
S3 confint.gam() method is not exported

### ISSUE THREAD

**Issue by choisy** [samclifford/mgcv.helper#2]
This is a very useful package, thanks for that!
A little issue is that your `confint.gam()` method is not exported, which forces the user to load the package with `library(mgcv.helper)` before using `confint()` and does not allow the user to directly use the `mgcv.helper::confint.gam()` call. This can be fixed by adding the `@export confint.gam` roxygen2 instruction in the header of the function, for example right before the `@export` instruction, as explained [here](https://stackoverflow.com/questions/46966169/s3methods-in-namespace-not-exported).

**Comment by samclifford** [comment]
Thanks, have now set this to be exported.
